server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml        # mybatis配置文件所在路径
  type-aliases-package: com.itheima.springcloud.pojo    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml                       # mapper映射文件

spring:
   application:
     name: hf-itheima-cloud-provider      # 重要, 名称很重要， 必须要写， 并且是唯一的
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://134.175.88.214:3306/cloudDB03?characterEncoding=utf-8
    # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  instance:
      instance-id: hf-itheima-cloud-provider:8003		#修改别名
      prefer-ip-address: true							#显示IP地址
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka            # 服务连接 Eureka server的地址
#      defaultZone: http://eureka01:7001/eureka/       # 服务连接 Eureka server的地址

info:
  app.name: hf-itheima-cloud-provider
  company.name: www.itheima.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$